In [1]:
########################################## Perfect Foresight planning ##########################################

# This Jupyter Notebook performs a deterministic planning simulation for each scenario of the simulation on energy investment and cost optimization.
# It includes the following steps:

# 1. Initialization of parameters, indication of the realised scenario.
# 2. Calculation of terminal value function using a deterministic approach.
# 3. Execution of a backward algorithm to optimize investment decisions over time.
# 4. Determination of initial investment values.
# 5. Saving the optimal investment path and exporting the results.

In [2]:
from results_writing import save_results_to_csv
from simulation_parameters import *
from load import *
from capacity_factors import CapacityFactor
from cost_functions import IterativeFunctions, InvestmentFunctions
from gradient_boost import GradientBoostingModel
from constraints import Constraints

sns.set_style('darkgrid')
plt.rcParams["figure.dpi"] = 500
np.set_printoptions(suppress=True, precision=5)
seed = 42

iterative_functions = IterativeFunctions()
cost_parameters = CostParameters()
investment_parameters = InvestmentParameters()
capacity_factors = CapacityFactor()
simu_parameters = SimulationParameters()
gradient_parameters = GradientParameters()
tech_parameters = TechnoParameters()
gen_scenario = Scenario()
d_reference = gen_scenario.average_scenario
investment_functions = InvestmentFunctions()
constraints = Constraints(simu_parameters.lambda_weight, simu_parameters.mu_weight, simu_parameters.kappa_weight, simu_parameters.nu_weight)
pct = cost_parameters.pc

time_start = time.time() 

print("Simulation name: " + simu_parameters.name)
print("Coal phase-out: " + simu_parameters.coal_phase_out)
print("Carbon tax: " + simu_parameters.carbon_tax)

time_start = time.time()

Directory already exists at: outputs/batch_simulations_review_test_load_growth
Simulation name: review_test_load_growth
Coal phase-out: n
Carbon tax: n


In [3]:
############################## 0.Initialization: Terminal Value ##############################

value_func_pf = np.zeros((simu_parameters.n_simu, simu_parameters.t, tech_parameters.n_w, tech_parameters.n_s, 
                          tech_parameters.n_g))
value_t = np.zeros((simu_parameters.n_simu, tech_parameters.n_w, tech_parameters.n_s, tech_parameters.n_g))

# Adjust for simulating a sample of the scenarios
low_bound = int(0)
high_bound = int(simu_parameters.n_simu)

for n in tqdm.tqdm(range(low_bound, high_bound)):
    print("Scenario " + str(n) + ": Beginning...")
    d_scenario = gen_scenario.scenarios[n]
    next_value = 0

    for t in tqdm.tqdm(range(simu_parameters.t-1, simu_parameters.t-2-simu_parameters.extension, -1)):
        ctax = simu_parameters.cpath[t]
        #at = load_curve[t]
        pct = cost_parameters.pc[t]
        kct = simu_parameters.kc[t]
        f_evol = cost_parameters.fossil_evol[t]
        d = d_scenario[t]
        #load = at + d_load[d]
        load = d_load[d]*(1 + simu_parameters.load_growth * t)
        epsval = capacity_factors.cap_factor[d]
        pv_cap = capacity_factors.pv_cf[d]
        pgt = cost_parameters.pg[d] * f_evol
        
        for w, s, g in product(range(len(tech_parameters.kw)), range(len(tech_parameters.ks)), 
                                         range(len(tech_parameters.kg))):
            cost_output = iterative_functions.cost(tech_parameters.kw[w], tech_parameters.kg[g], kct, 
                                                   tech_parameters.ks[s], load, pv_cap, epsval, pgt, pct, ctax)
            cost = cost_output[0].sum()
            carbon_realised = cost_output[1].sum()

            mu_constraint = constraints.compute_mu_constraint(t, tech_parameters.kg[g])
            kappa_constraint = constraints.compute_kappa_constraint(t, tech_parameters.kw[w])
            nu_constraint = constraints.compute_nu_constraint(t, tech_parameters.ks[s])
            lambda_constraint = constraints.compute_lambda_constraint(t, carbon_realised)

            value_func_pf[n, t, w, s, g] = cost + lambda_constraint + mu_constraint + kappa_constraint + nu_constraint

        value_func_pf[n, t] += simu_parameters.beta*next_value
        next_value = value_func_pf[n, t]

    # Gradient Boost approximation
    value_t[n] = value_func_pf[n, simu_parameters.t-simu_parameters.extension-1]

    finalvalue = GradientBoostingModel(tech_parameters.kw, tech_parameters.ks, tech_parameters.kg, d)
    finalvalue.train_data = value_t[n]
    mse_in, mse_out, X_train, X_test, y_train, y_test, X_mean, X_std, y_mean, y_std = finalvalue.train_deterministic()
    finalvalue.save_model(simu_parameters.path_functions + "\\value_func_pf_numero_" + str(n) + "_time_" 
                          + str(simu_parameters.t-simu_parameters.extension) + ".pkl")

time_elapsed = (time.time() - time_start)
print(time_elapsed/60, "min")

  0%|          | 0/64 [00:00<?, ?it/s]

Scenario 0: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  2%|▏         | 1/64 [04:38<4:52:14, 278.33s/it]

Scenario 1: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  3%|▎         | 2/64 [07:42<3:50:38, 223.20s/it]

Scenario 2: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  5%|▍         | 3/64 [11:27<3:47:39, 223.93s/it]

Scenario 3: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  6%|▋         | 4/64 [15:10<3:43:16, 223.28s/it]

Scenario 4: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  8%|▊         | 5/64 [18:25<3:29:48, 213.36s/it]

Scenario 5: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  9%|▉         | 6/64 [21:48<3:22:38, 209.62s/it]

Scenario 6: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 11%|█         | 7/64 [25:26<3:21:56, 212.57s/it]

Scenario 7: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 12%|█▎        | 8/64 [29:05<3:20:16, 214.59s/it]

Scenario 8: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 14%|█▍        | 9/64 [32:16<3:09:54, 207.17s/it]

Scenario 9: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 16%|█▌        | 10/64 [35:53<3:09:10, 210.20s/it]

Scenario 10: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 17%|█▋        | 11/64 [39:35<3:08:51, 213.81s/it]

Scenario 11: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 19%|█▉        | 12/64 [43:09<3:05:24, 213.94s/it]

Scenario 12: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 20%|██        | 13/64 [46:33<2:59:18, 210.95s/it]

Scenario 13: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 22%|██▏       | 14/64 [49:40<2:49:35, 203.51s/it]

Scenario 14: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 23%|██▎       | 15/64 [52:18<2:35:06, 189.92s/it]

Scenario 15: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 25%|██▌       | 16/64 [54:55<2:23:58, 179.97s/it]

Scenario 16: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 27%|██▋       | 17/64 [57:43<2:18:09, 176.37s/it]

Scenario 17: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 28%|██▊       | 18/64 [1:00:43<2:15:58, 177.36s/it]

Scenario 18: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 30%|██▉       | 19/64 [1:04:05<2:18:34, 184.77s/it]

Scenario 19: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 31%|███▏      | 20/64 [1:07:54<2:25:12, 198.02s/it]

Scenario 20: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 33%|███▎      | 21/64 [1:11:35<2:27:02, 205.16s/it]

Scenario 21: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 34%|███▍      | 22/64 [1:14:13<2:13:39, 190.95s/it]

Scenario 22: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 36%|███▌      | 23/64 [1:16:48<2:03:07, 180.17s/it]

Scenario 23: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 38%|███▊      | 24/64 [1:19:19<1:54:08, 171.22s/it]

Scenario 24: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 39%|███▉      | 25/64 [1:21:51<1:47:43, 165.74s/it]

Scenario 25: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 41%|████      | 26/64 [1:24:41<1:45:37, 166.77s/it]

Scenario 26: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 42%|████▏     | 27/64 [1:27:05<1:38:36, 159.91s/it]

Scenario 27: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 44%|████▍     | 28/64 [1:29:31<1:33:26, 155.75s/it]

Scenario 28: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 45%|████▌     | 29/64 [1:32:00<1:29:45, 153.86s/it]

Scenario 29: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 47%|████▋     | 30/64 [1:34:28<1:26:15, 152.23s/it]

Scenario 30: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 48%|████▊     | 31/64 [1:37:10<1:25:17, 155.08s/it]

Scenario 31: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 50%|█████     | 32/64 [1:39:43<1:22:21, 154.42s/it]

Scenario 32: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 52%|█████▏    | 33/64 [1:42:08<1:18:17, 151.53s/it]

Scenario 33: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 53%|█████▎    | 34/64 [1:44:40<1:15:48, 151.62s/it]

Scenario 34: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 55%|█████▍    | 35/64 [1:46:56<1:11:00, 146.91s/it]

Scenario 35: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 56%|█████▋    | 36/64 [1:49:17<1:07:46, 145.25s/it]

Scenario 36: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 58%|█████▊    | 37/64 [1:51:31<1:03:50, 141.88s/it]

Scenario 37: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 59%|█████▉    | 38/64 [1:53:47<1:00:42, 140.08s/it]

Scenario 38: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 61%|██████    | 39/64 [1:56:07<58:24, 140.18s/it]  

Scenario 39: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 62%|██████▎   | 40/64 [1:58:31<56:28, 141.20s/it]

Scenario 40: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 64%|██████▍   | 41/64 [2:01:00<55:05, 143.71s/it]

Scenario 41: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 66%|██████▌   | 42/64 [2:03:10<51:06, 139.39s/it]

Scenario 42: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 67%|██████▋   | 43/64 [2:05:19<47:40, 136.24s/it]

Scenario 43: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 69%|██████▉   | 44/64 [2:07:19<43:51, 131.56s/it]

Scenario 44: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 70%|███████   | 45/64 [2:09:29<41:28, 130.98s/it]

Scenario 45: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 72%|███████▏  | 46/64 [2:11:29<38:20, 127.82s/it]

Scenario 46: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 73%|███████▎  | 47/64 [2:13:39<36:21, 128.35s/it]

Scenario 47: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 75%|███████▌  | 48/64 [2:15:56<34:57, 131.08s/it]

Scenario 48: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 77%|███████▋  | 49/64 [2:18:14<33:14, 132.96s/it]

Scenario 49: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 78%|███████▊  | 50/64 [2:20:28<31:06, 133.31s/it]

Scenario 50: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 80%|███████▉  | 51/64 [2:22:49<29:24, 135.71s/it]

Scenario 51: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 81%|████████▏ | 52/64 [2:25:11<27:29, 137.46s/it]

Scenario 52: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 83%|████████▎ | 53/64 [2:27:23<24:54, 135.89s/it]

Scenario 53: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 84%|████████▍ | 54/64 [2:29:37<22:34, 135.47s/it]

Scenario 54: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 86%|████████▌ | 55/64 [2:31:38<19:37, 130.87s/it]

Scenario 55: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 88%|████████▊ | 56/64 [2:33:31<16:44, 125.55s/it]

Scenario 56: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 89%|████████▉ | 57/64 [2:35:40<14:47, 126.80s/it]

Scenario 57: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 91%|█████████ | 58/64 [2:37:38<12:24, 124.06s/it]

Scenario 58: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 92%|█████████▏| 59/64 [2:39:40<10:17, 123.43s/it]

Scenario 59: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 94%|█████████▍| 60/64 [2:41:38<08:06, 121.73s/it]

Scenario 60: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 95%|█████████▌| 61/64 [2:43:45<06:10, 123.37s/it]

Scenario 61: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 97%|█████████▋| 62/64 [2:45:59<04:13, 126.69s/it]

Scenario 62: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

 98%|█████████▊| 63/64 [2:48:11<02:08, 128.10s/it]

Scenario 63: Beginning...


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

100%|██████████| 64/64 [2:50:15<00:00, 159.61s/it]

170.25381629864376 min


In [4]:
############################## 1.Backward algorithm ##############################

perfect_foresight_optimal_trajectory = np.zeros((simu_parameters.n_simu, simu_parameters.t-simu_parameters.extension, 3))

for n in tqdm.tqdm(range(low_bound, high_bound)):
    
    print("Simulation " + str(n))

    d_scenario = gen_scenario.scenarios[n]
    next_value_func_pf = GradientBoostingModel(tech_parameters.kw, tech_parameters.ks, tech_parameters.kg)
    next_value_func_pf.train_data = value_t[n]
    next_value_func_pf.model, next_value_func_pf.scaler_X, next_value_func_pf.scaler_y, next_value_func_pf.train_data_mean, next_value_func_pf.train_data_std = next_value_func_pf.load_model(simu_parameters.path_functions + "\\value_func_pf_numero_" + str(n) + "_time_" + str(simu_parameters.t-simu_parameters.extension) + ".pkl")

    for t in tqdm.tqdm(range(simu_parameters.t-simu_parameters.extension-2, -1, -1)):
        ctax = simu_parameters.cpath[t]
        #at = load_curve[t]
        pct = cost_parameters.pc[t]
        kct = simu_parameters.kc[t]
        f_evol = cost_parameters.fossil_evol[t]
        d = d_scenario[t]
        #load = at + d_load[d]
        load = d_load[d]*(1 + simu_parameters.load_growth * t)
        epsval = capacity_factors.cap_factor[d]
        pv_cap = capacity_factors.pv_cf[d]
        pgt = cost_parameters.pg[d] * f_evol
        for w, s, g in product(range(len(tech_parameters.kw)), range(len(tech_parameters.ks)), 
                               range(len(tech_parameters.kg))):
            X, Y, Z = np.meshgrid(np.linspace(tech_parameters.kwlow - tech_parameters.kw[w], 
                                              tech_parameters.kwbound - tech_parameters.kw[w], tech_parameters.n_w),
                              np.linspace(tech_parameters.kslow - tech_parameters.ks[s], 
                                          tech_parameters.ksbound - tech_parameters.ks[s], tech_parameters.n_s),
                              np.linspace(tech_parameters.kglow - tech_parameters.kg[g], 
                                          tech_parameters.kgbound - tech_parameters.kg[g], tech_parameters.n_g), indexing='ij')

            grid = investment_functions.invest(X, Y, Z, t) + (simu_parameters.beta)*(value_func_pf[n, t+1])
            grid_minimum = np.unravel_index(np.argmin(grid), grid.shape)

            cost_output = iterative_functions.cost(tech_parameters.kw[w], tech_parameters.kg[g], kct, tech_parameters.ks[s], 
                                                   load, pv_cap, epsval, pgt, pct, ctax)
            cost = cost_output[0].sum()
            carbon_realised = cost_output[1].sum()

            mu_constraint = constraints.compute_mu_constraint(t, tech_parameters.kg[g])
            kappa_constraint = constraints.compute_kappa_constraint(t, tech_parameters.kw[w])
            nu_constraint = constraints.compute_nu_constraint(t, tech_parameters.ks[s])
            lambda_constraint = constraints.compute_lambda_constraint(t, carbon_realised)

            next_value = next_value_func_pf.minimize_quantity(tech_parameters.kw[w], tech_parameters.ks[s], 
                                                              tech_parameters.kg[g], t, grid_minimum)[3]
            
            value_func_pf[n, t, w, s, g] = cost + lambda_constraint + mu_constraint + kappa_constraint + nu_constraint + simu_parameters.beta * next_value

        value_t = value_func_pf[n, t]
        model = GradientBoostingModel(tech_parameters.kw, tech_parameters.ks, tech_parameters.kg)
        model.train_data = value_t
        mse_in, mse_out, X_train, X_test, y_train, y_test, X_mean, X_std, y_mean, y_std = model.train_deterministic()

        model.save_model(simu_parameters.path_functions + "\\value_func_pf_numero_" + str(n) + "_time_" + str(t) + ".pkl")
        next_value_func_pf = GradientBoostingModel(tech_parameters.kw, tech_parameters.ks, tech_parameters.kg)
        next_value_func_pf.train_data = value_t
        model, scaler_X, scaler_y, train_data_mean, train_data_std = next_value_func_pf.load_model(simu_parameters.path_functions + "\\value_func_pf_numero_" + str(n) + "_time_" + str(t) + ".pkl")
        next_value_func_pf.model = model
        next_value_func_pf.scaler_X = scaler_X
        next_value_func_pf.scaler_y = scaler_y

    X0, Y0, Z0 = np.meshgrid(np.linspace(tech_parameters.kwlow - tech_parameters.kw0, 
                                         tech_parameters.kwbound - tech_parameters.kw0, tech_parameters.n_w),
                             np.linspace(tech_parameters.kslow - tech_parameters.ks0, 
                                         tech_parameters.ksbound - tech_parameters.ks0, tech_parameters.n_s),
                             np.linspace(tech_parameters.kglow - tech_parameters.kg0, 
                                         tech_parameters.kgbound - tech_parameters.kg0, tech_parameters.n_g), indexing='ij')

    invest_initial = investment_functions.invest(X0, Y0, Z0, t)
    value_func_pf[n, 0] = value_func_pf[n, 0] + invest_initial

    final_model = GradientBoostingModel(tech_parameters.kw, tech_parameters.ks, tech_parameters.kg)

    final_model.train_data = value_func_pf[n, 0]
    mse_in, mse_out, X_train, X_test, y_train, y_test, X_mean, X_std, y_mean, y_std = final_model.train_deterministic()

    final_model.save_model(simu_parameters.path_functions + "\\value_pf_numero_" + str(n) + "_0.pkl")

    perfect_foresight_optimal_trajectory[n, 0] = [tech_parameters.kw0, tech_parameters.ks0, tech_parameters.kg0]
    kw_t, ks_t, kg_t = tech_parameters.kw0, tech_parameters.ks0, tech_parameters.kg0

    for t in range(0, simu_parameters.t-simu_parameters.extension-1):
        model, scaler_X, scaler_y, train_data_mean, train_data_std = final_model.load_model(simu_parameters.path_functions + "\\value_func_pf_numero_" + str(n) + "_time_" + str(t) + ".pkl")
        final_model.model = model
        final_model.scaler_X = scaler_X
        final_model.scaler_y = scaler_y
        X, Y, Z = np.meshgrid(np.linspace(tech_parameters.kwlow - kw_t, 
                                          tech_parameters.kwbound - kw_t, tech_parameters.n_w),
                                  np.linspace(tech_parameters.kslow - ks_t, 
                                              tech_parameters.ksbound - ks_t, tech_parameters.n_s),
                                  np.linspace(tech_parameters.kglow - kg_t, 
                                              tech_parameters.kgbound - kg_t, tech_parameters.n_g), indexing='ij')

        grid = investment_functions.invest(X, Y, Z, t) + (simu_parameters.beta)*(value_func_pf[n, t+1])
        grid_minimum = np.unravel_index(np.argmin(grid), grid.shape)
        kw_t, ks_t, kg_t, value = final_model.minimize_quantity(kw_t, ks_t, kg_t, t, grid_minimum)
        perfect_foresight_optimal_trajectory[n, t+1] = [kw_t, ks_t, kg_t]
        
    print("Perfect foresight trajectory n°", n, perfect_foresight_optimal_trajectory[n])
    
    perfect_foresight_optimal_df = pd.DataFrame(perfect_foresight_optimal_trajectory[n], columns=['KW', 'KPV', 'KG'])
    perfect_foresight_optimal_df.to_csv(os.path.join(simu_parameters.path_perfectforesight, 'perfect_foresight_optimal_trajectory_'+str(n)+'.csv'), index=False)

col_names = np.arange(low_bound, high_bound, 1)
save_results_to_csv('perfect_foresight', perfect_foresight_optimal_trajectory[low_bound:high_bound], 
                    int(simu_parameters.n_simu), column_names = col_names)
for n in tqdm.tqdm(range(low_bound, high_bound)):
    perfect_foresight_optimal_df = pd.DataFrame(perfect_foresight_optimal_trajectory[n], columns=['KW', 'KPV', 'KG'])
    perfect_foresight_optimal_df.to_csv(os.path.join(simu_parameters.path_deterministic, 
                                                     'perfect_foresight_optimal_trajectory_'+str(n)+'.csv'), index=False)
    
time_elapsed = (time.time() - time_start)
print(time_elapsed/60, "min")

  0%|          | 0/64 [00:00<?, ?it/s]

Simulation 0


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  2%|▏         | 1/64 [3:53:32<245:13:23, 14012.75s/it]

Perfect foresight trajectory n° 0 [[60000. 76600. 36000.]
 [60000. 76000. 46000.]
 [60000. 76000. 46000.]
 [60000. 76000. 49000.]
 [60000. 76000. 50000.]
 [60000. 76000. 50000.]
 [60000. 76000. 51000.]
 [60000. 76000. 51000.]
 [60000. 76000. 51000.]
 [60000. 76000. 51500.]
 [60000. 76000. 52500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54000.]]
Simulation 1


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  3%|▎         | 2/64 [5:32:42<159:38:59, 9269.99s/it] 

Perfect foresight trajectory n° 1 [[60000. 76600. 36000.]
 [60000. 76000. 48500.]
 [60000. 76000. 49500.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54000.]]
Simulation 2


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  5%|▍         | 3/64 [7:04:11<127:49:05, 7543.36s/it]

Perfect foresight trajectory n° 2 [[60000. 76600. 36000.]
 [60000. 76000. 44500.]
 [60000. 76000. 48000.]
 [60000. 76000. 49500.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54000.]
 [60000. 76000. 54500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54500.]]
Simulation 3


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  6%|▋         | 4/64 [8:39:40<113:46:58, 6826.98s/it]

Perfect foresight trajectory n° 3 [[60000. 76600. 36000.]
 [60000. 76000. 47500.]
 [60000. 76000. 49500.]
 [60000. 76000. 51000.]
 [60000. 76000. 51000.]
 [60000. 76000. 51000.]
 [60000. 76000. 51500.]
 [60000. 76000. 53500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54000.]
 [60000. 76000. 55000.]]
Simulation 4


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  8%|▊         | 5/64 [10:12:50<104:34:42, 6381.06s/it]

Perfect foresight trajectory n° 4 [[60000. 76600. 36000.]
 [60000. 76000. 47500.]
 [60000. 76000. 48500.]
 [60000. 76000. 49000.]
 [60000. 76000. 50000.]
 [60000. 76000. 53500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54500.]
 [60000. 76000. 55000.]
 [60000. 76000. 55000.]
 [60000. 76000. 54500.]]
Simulation 5


  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  0%|          | 0/1476 [00:00<?, ?it/s]

  9%|▉         | 6/64 [11:49:05<114:14:33, 7090.92s/it]

Perfect foresight trajectory n° 5 [[60000. 76600. 36000.]
 [60000. 76000. 52500.]
 [60000. 76000. 53000.]
 [60000. 76000. 53000.]
 [60000. 76000. 53000.]
 [60000. 76000. 53000.]
 [60000. 76000. 53000.]
 [60000. 76000. 52500.]
 [60000. 76000. 52500.]
 [60000. 76000. 54500.]
 [60000. 76000. 54000.]
 [60000. 76000. 55000.]
 [60000. 76000. 54500.]]
Simulation 6


IndexError: index 6 is out of bounds for axis 0 with size 6